### ISSUE TITLE
Picture size issue

### ISSUE THREAD

**Issue by rudrab** [GustavoPeredo/Big-Avatar-Gnome-Shell-Extension#2]
Dear Gustavo,
Nice extension. Before installing, I was not aware that I need that (ala iphone :)).
But I am facing one issue. If I shrink the picture size (from default 144),  its no more circular,  just cropped in y direction, while in x direction, its still default. 

May I request you to apply the radius in both side, or control the x-y value separately?

**Comment by GustavoPeredo** [comment]
Thanks for your issue! Yes, I'm thinking of of updating the extension soon, some users also requested to open user account settings on click. Your suggestion and theirs are on my to-do list, just have to find time for them.

Thanks again for the suggestion

**Comment by GustavoPeredo** [comment]
Hello, It's been a while since I coded something related to this extension. Good news and bad news!
Good news: The icon won't be cropped anymore, because now I use the default Gnome widget you see on the login screen
Bad news: There is no easy way of choosing the size of the picture
Thanks for your comment once again :3
